source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RoverCocoTest_Example', :exclusive => true do
  pod 'RoverCocoTest', :path => '../'
end

target 'RoverCocoTest_Tests', :exclusive => true do
  pod 'RoverCocoTest', :path => '../'

  pod 'FBSnapshotTestCase'
end
